In [1]:
print("Hello World")

Hello World

#PM Task
Load the two datasets
Clean the them (thoroughly)
Measure at least 1 data engineering metric in the data cleaning process (ie dropped rows)
MVP: Output the cleaned files as a local csv.
Stretch:

Output the cleaned files into the local SSMS (use SQLAlchemy); create a new DB for this.
Refactor your code into modular functions.

In [1]:
import pandas as pd

In [43]:
# Reading both sets of data

Book_Data = pd.read_csv ('03_Library Systembook.csv')
Customer_Data = pd.read_csv ('03_Library SystemCustomers.csv')

print(Book_Data.head())
print(Customer_Data.head())

    Id                                     Books Book checkout Book Returned  \
0  1.0                       Catcher in the Rye   "20/02/2023"    25/02/2023
1  2.0          Lord of the rings the two towers  "24/03/2023"    21/03/2023
2  3.0  Lord of the rings the return of the kind  "29/03/2023"    25/03/2023
3  4.0                                The hobbit  "02/04/2023"    25/03/2023
4  5.0                                     Dune   "02/04/2023"    25/03/2023

  Days allowed to borrow  Customer ID
0                2 weeks          1.0
1                2 weeks          2.0
2                2 weeks          3.0
3                2 weeks          4.0
4                2 weeks          5.0
   Customer ID   Customer Name
0          1.0        Jane Doe
1          2.0      John Smith
2          3.0      Dan Reeves
3          NaN             NaN
4          5.0  William Holden

In [44]:
Customer_Data.drop_duplicates
Book_Data.drop_duplicates

<bound method DataFrame.drop_duplicates of       Id                                     Books Book checkout  \
0    1.0                       Catcher in the Rye   "20/02/2023"
1    2.0          Lord of the rings the two towers  "24/03/2023"
2    3.0  Lord of the rings the return of the kind  "29/03/2023"
3    4.0                                The hobbit  "02/04/2023"
4    5.0                                     Dune   "02/04/2023"
..   ...                                       ...           ...
109  NaN                                       NaN           NaN
110  NaN                                       NaN           NaN
111  NaN                                       NaN           NaN
112  NaN                                       NaN           NaN
113  NaN                                       NaN           NaN

    Book Returned Days allowed to borrow  Customer ID
0      25/02/2023                2 weeks          1.0
1      21/03/2023                2 weeks          2.0
2      25/03/2023                2 weeks          3.0
3      25/03/2023                2 weeks          4.0
4      25/03/2023                2 weeks          5.0
..            ...                    ...          ...
109           NaN                    NaN          NaN
110           NaN                    NaN          NaN
111           NaN                    NaN          NaN
112           NaN                    NaN          NaN
113           NaN                    NaN          NaN

[114 rows x 6 columns]>

In [50]:
Book_Data.dropna(thresh=2)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,20/02/2023,25/02/2023,2 weeks,1.0
1,2.0,Lord of the rings the two towers,24/03/2023,21/03/2023,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,29/03/2023,25/03/2023,2 weeks,3.0
3,4.0,The hobbit,02/04/2023,25/03/2023,2 weeks,4.0
4,5.0,Dune,02/04/2023,25/03/2023,2 weeks,5.0
5,6.0,Little Women,02/04/2023,01/05/2023,2 weeks,1.0
6,7.0,IT,10/04/2063,03/04/2023,2 weeks,6.0
7,8.0,Misery,15/04/2023,03/04/2023,2 weeks,7.0
8,9.0,Catch 22,15/04/2023,16/04/2023,2 weeks,7.0
9,10.0,Animal Farm,20/04/2023,24/04/2023,2 weeks,2.0
10,11.0,1984,23/04/2023,27/04/2023,2 weeks,8.0
11,12.0,Little Women,02/04/2023,01/05/2023,2 weeks,1.0
12,13.0,East of Eden,30/04/2023,05/05/2023,2 weeks,2.0
13,14.0,America Is in the Heart,01/05/2023,07/05/2023,2 weeks,3.0
14,15.0,Wuthering Heights,01/05/2023,10/05/2023,2 weeks,9.0
15,16.0,Dark Tales,15/05/2023,01/06/2023,2 weeks,2.0
17,18.0,Les Miserables,03/06/2023,07/06/2023,2 weeks,5.0
18,19.0,Dracula,10/06/2023,10/07/2023,2 weeks,10.0
19,20.0,Frankenstein,01/06/2023,20/06/2023,2 weeks,2.0
20,21.0,NaN,01/06/2023,05/06/2023,2 weeks,NaN

In [51]:
try:
    Book_Data['Book checkout'] = Book_Data['Book checkout'].str.replace('"',"",regex=True)
    Book_Data['Book checkout'] = pd.to_datetime(Book_Data['Book checkout'], format='mixed')
    Book_Data.head()
except Exception as e:
    print(f"Error Occured: {e}")

In [52]:
Book_Data.iloc[16]

Id                                       18.0
Books                          Les Miserables
Book checkout             2023-03-06 00:00:00
Book Returned                      07/06/2023
Days allowed to borrow                2 weeks
Customer ID                               5.0
Name: 17, dtype: object

In [53]:
Book_Data.drop(16, inplace=True)
dropCount += 1

KeyError: '[16] not found in axis'

In [35]:
Customer_Data.dropna(thresh=1)

   Customer ID     Customer Name
0          1.0          Jane Doe
1          2.0        John Smith
2          3.0        Dan Reeves
4          5.0    William Holden
5          6.0     Jaztyn Forest
6          7.0     Jackie Irving
7          8.0  Matthew Stirling
8          9.0         Emory Ted

In [34]:
print(data())

      Id                                     Books Book checkout  \
0    1.0                       Catcher in the Rye   "20/02/2023"
1    2.0          Lord of the rings the two towers  "24/03/2023"
2    3.0  Lord of the rings the return of the kind  "29/03/2023"
3    4.0                                The hobbit  "02/04/2023"
4    5.0                                     Dune   "02/04/2023"
5    6.0                              Little Women  "02/04/2023"
6    7.0                                        IT  "10/04/2063"
7    8.0                                   Misery   "15/04/2023"
8    9.0                                  Catch 22  "15/04/2023"
9   10.0                              Animal Farm   "20/04/2023"
10  11.0                                      1984  "23/04/2023"
11  12.0                              Little Women  "02/04/2023"
12  13.0                              East of Eden  "30/04/2023"
13  14.0                   America Is in the Heart  "01/05/2023"
14  15.0                         Wuthering Heights  "01/05/2023"
15  16.0                                Dark Tales  "15/05/2023"
16  17.0                        The Bloody Chamber  "32/05/2023"
17  18.0                            Les Miserables  "03/06/2023"
18  19.0                                   Dracula  "10/06/2023"
19  20.0                              Frankenstein  "01/06/2023"
20  21.0                                       NaN  "01/06/2023"
21   NaN                                       NaN           NaN

   Book Returned Days allowed to borrow  Customer ID
0     25/02/2023                2 weeks          1.0
1     21/03/2023                2 weeks          2.0
2     25/03/2023                2 weeks          3.0
3     25/03/2023                2 weeks          4.0
4     25/03/2023                2 weeks          5.0
5     01/05/2023                2 weeks          1.0
6     03/04/2023                2 weeks          6.0
7     03/04/2023                2 weeks          7.0
8     16/04/2023                2 weeks          7.0
9     24/04/2023                2 weeks          2.0
10    27/04/2023                2 weeks          8.0
11    01/05/2023                2 weeks          1.0
12    05/05/2023                2 weeks          2.0
13    07/05/2023                2 weeks          3.0
14    10/05/2023                2 weeks          9.0
15    01/06/2023                2 weeks          2.0
16    04/06/2023                2 weeks          3.0
17    07/06/2023                2 weeks          5.0
18    10/07/2023                2 weeks         10.0
19    20/06/2023                2 weeks          2.0
20    05/06/2023                2 weeks          NaN
21           NaN                    NaN          NaN